### ISSUE TITLE
Update to libtidy 5.6.0

### ISSUE THREAD

**Issue by cmb69** [winlibs/libtidy#2]
Otherwise users might hit <https://bugs.php.net/bug.php?id=76992> and maybe other issues.

**Comment by weltling** [comment]
Thanks for the ping, @cmb69. The version 5.6.0 caused some tests to fail in PHP last time I tried it, so I was basically waiting for a version up. I'll check to apply some patches to 5.4.0 first, at least for use with the stable branches.

Thanks.

**Comment by cmb69** [comment]
@weltling Hmm, it seems all ext/tidy/tests/ are passing on Linux with libtidy 5.6.0 (even when run with valgrind), but of course there may be issues. At least <https://bugs.php.net/bug.php?id=76683> is unfortunate.

**Comment by weltling** [comment]
I've just tried again, but nothing changed. 

```
$ type ext\tidy\tests\020.diff
003- <?xml version="1.0" encoding="iso-8859-1"?>
```

I see also that i've fixed one test back then http://git.php.net/?p=php-src.git;a=commitdiff;h=83a77383b92d8b1b1a5c141c10e9342aa64b1d92 . I'd tend to applying a patch to 5.4.0 in this case, if one can find one.

Thanks.

**Comment by cmb69** [comment]
I can confirm that ext/tidy/tests/020.phpt fails with libtidy 5.6.0 (the only failing test).

> I'd tend to applying a patch to 5.4.0 in this case, if one can find one.

I've applied https://github.com/htacg/tidy-html5/pull/622/ (only clean.c), but the segfault remains. Phew!

**Comment by weltling** [comment]
Heh, that's itchy. Perhaps some follow up patch fixes the test issue, then upgrading to 5.6.0 could work out. I'll be able to check through the tidy repository close to weekend.

Another course of action might be to take some untagged 5.7.x or downgrade to previous 5.2.0.

Thanks.

**Comment by cmb69** [comment]
Applying htacg/tidy-html5@67eaeb6d18563e223344b00f98d6ad42000d8285 (no conflicts) to libtidy 5.6.0 lets all tidy tests succeed again (without memory leaks). Might be the best way forward for now.

**Comment by weltling** [comment]
Many thanks for the research, Christoph! I'll check and build it next days so it can go into staging.

Thanks.

**Comment by weltling** [comment]
The upgraded lib has been put into staging as discussed. Thanks!

**Comment by cmb69** [comment]
Great! Thanks, Anatol.
