### ISSUE TITLE
libtidy 5.6.0 changes locale

### ISSUE THREAD

**Issue by cmb69** [winlibs/libtidy#3]
This has been reported as [PHP bug 77278](https://bugs.php.net/bug.php?id=77278). Simple reproducer on a system with a German locale (or any other which uses a comma as decimal separator):
````php
<?php
$val = 4/3;
echo "$val\n";
new tidy;
echo "$val\n";
````
This gives:
````
1.3333333333333
1,3333333333333
````
While this is clearly an upstream issue (htacg/tidy-html5#780), maybe a resonable workaround for now could be to do `cmake -DSUPPORT_LOCALIZATIONS=OFF …` (tested on Linux; no other regression detected).

**Comment by weltling** [comment]
Thanks for the ping. The current tag has been rebuilt according to your suggestion, the binaries has been put into staging, so should be included with the upcoming RCs. I didn't document this, as this probably won't be needed when upgrading libtidy later.

Thanks.
